parameters:
    senky.structureddata.sameas:
        - 'facebook'
        - 'twitter'
        - 'instagram'
        - 'youtube'
        - 'linkedin'
        - 'myspace'
        - 'pinterest'
        - 'soundcloud'
        - 'tumblr'
