imports:
    - { resource: parameters.yml }

services:
    senky.structureddata.controller.acp:
        class: senky\structureddata\controller\acp_controller
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@ext.manager'
            - '%senky.structureddata.sameas%'

    senky.structureddata.listener:
        class: senky\structureddata\event\main_listener
        arguments:
            - '@template'
            - '@config'
            - '%core.php_ext%'
            - '%senky.structureddata.sameas%'
        tags:
            - { name: event.listener }
